### PR TITLE
Update to 4.3.4

### PR DESCRIPTION
**Pull request by ocefpaf**

### CODE REVIEW

**Comment by nicoddemus** [comment]
I believe this can be changed to `noarch: python`.

**Comment by ocefpaf** [comment]
> I believe this can be changed to `noarch: python`.

I guess so if `futures  # [py27]` can be installed safely on py3k. Let's test that.

**Comment by ocefpaf** [comment]
@conda-forge-admin, please add noarch: python

**Comment by nicoddemus** [comment]
Yeah no good:

```
The following specifications were found to be in conflict:
  - futures -> python 2.6*
  - python 3.6.*
Use "conda info <package>" to see the dependencies for each package.
```

Sorry for the noise! I actually didn't look at your recipe (duh) but at the `master`'s recipe which didn't have `future` as dependency, that's why I suggested adding `noarch: python`.

**Comment by ocefpaf** [comment]
NP. It was easier to make the changes than google about `futures` :smile:

**Comment by ocefpaf** [comment]
@conda-forge-admin, please rerender

**Review by nicoddemus — APPROVED** [review]

**Pull request merged**
